#!/usr/bin/env python3
"""
TikTok自動アップロードスクリプト

使用方法:
    python upload_tiktok.py --video video.mp4 --title "動画タイトル"

環境変数:
    TIKTOK_SESSIONID: TikTokのsessionid Cookie
"""

import os
import sys
import argparse
import json
import tempfile
from pathlib import Path
from datetime import datetime


def create_cookies_file(sessionid: str, output_path: str) -> bool:
    """
    sessionidからNetscape形式のcookies.txtを生成

    Args:
        sessionid: TikTokのsessionid Cookie値
        output_path: 出力ファイルパス

    Returns:
        bool: 成功時True
    """
    # Netscape cookies.txt形式
    # domain, include_subdomains, path, secure, expiry, name, value
    cookies_content = f"""# Netscape HTTP Cookie File
# This file was generated by upload_tiktok.py

.tiktok.com	TRUE	/	TRUE	1893456000	sessionid	{sessionid}
.tiktok.com	TRUE	/	TRUE	1893456000	sessionid_ss	{sessionid}
"""

    try:
        with open(output_path, 'w') as f:
            f.write(cookies_content)
        return True
    except Exception as e:
        print(f"[TikTok] Cookie file creation error: {e}")
        return False


def generate_tiktok_description(title: str, youtube_description: str = None) -> str:
    """
    TikTok用の説明文を生成

    Args:
        title: 動画タイトル
        youtube_description: YouTube用の説明文（あれば）

    Returns:
        TikTok用の説明文（ハッシュタグ付き）
    """
    # TikTok用ハッシュタグ（ユーザー指定）
    hashtags = [
        "#年金",
        "#シニア",
        "#60代",
        "#老後",
        "#お金の話",
        "#節約生活",
    ]

    # タイトルをそのまま使用
    description = f"{title}\n\n{' '.join(hashtags)}"

    return description


def upload_to_tiktok(
    video_path: str,
    title: str,
    sessionid: str,
    youtube_description: str = None
) -> dict:
    """
    TikTokに動画をアップロード

    Args:
        video_path: 動画ファイルパス
        title: 動画タイトル
        sessionid: TikTokのsessionid
        youtube_description: YouTube用の説明文

    Returns:
        dict: 結果情報
    """
    result = {
        "success": False,
        "error": None,
        "video_path": video_path,
    }

    # 動画ファイルの存在確認
    if not os.path.exists(video_path):
        result["error"] = f"Video file not found: {video_path}"
        return result

    # sessionidの確認
    if not sessionid:
        result["error"] = "TIKTOK_SESSIONID is not set"
        return result

    try:
        # tiktok-uploaderをインポート
        try:
            from tiktok_uploader.upload import upload_video
        except ImportError:
            result["error"] = "tiktok-uploader is not installed. Run: pip install tiktok-uploader"
            return result

        # Cookie ファイルを作成
        temp_dir = tempfile.mkdtemp()
        cookies_path = os.path.join(temp_dir, "cookies.txt")

        if not create_cookies_file(sessionid, cookies_path):
            result["error"] = "Failed to create cookies file"
            return result

        # TikTok用の説明文を生成
        description = generate_tiktok_description(title, youtube_description)

        print(f"[TikTok] Uploading: {video_path}")
        print(f"[TikTok] Description: {description[:100]}...")

        # アップロード実行
        # headless=True でブラウザを表示しない（GitHub Actions用）
        upload_video(
            filename=video_path,
            description=description,
            cookies=cookies_path,
            headless=True,
        )

        result["success"] = True
        result["description"] = description
        print("[TikTok] Upload successful!")

        # Cookie ファイルを削除
        try:
            os.remove(cookies_path)
            os.rmdir(temp_dir)
        except:
            pass

    except Exception as e:
        error_msg = str(e)
        result["error"] = error_msg
        print(f"[TikTok] Upload failed: {error_msg}")

        # よくあるエラーの対処法を表示
        if "sessionid" in error_msg.lower() or "cookie" in error_msg.lower():
            print("[TikTok] Hint: sessionid may be expired. Please update TIKTOK_SESSIONID.")
        elif "too many" in error_msg.lower():
            print("[TikTok] Hint: Too many uploads. Wait a few hours before trying again.")

    return result


def send_discord_notification(webhook_url: str, result: dict, video_title: str):
    """
    Discord通知を送信

    Args:
        webhook_url: Discord Webhook URL
        result: アップロード結果
        video_title: 動画タイトル
    """
    if not webhook_url:
        return

    try:
        import requests

        if result["success"]:
            message = f"🎵 **TikTok投稿完了**\n\n📹 {video_title[:50]}"
        else:
            message = f"⚠️ **TikTok投稿失敗**\n\n📹 {video_title[:50]}\n❌ {result.get('error', 'Unknown error')[:200]}"

        requests.post(
            webhook_url,
            json={"content": message},
            timeout=10
        )
    except Exception as e:
        print(f"[Discord] Notification failed: {e}")


def main():
    parser = argparse.ArgumentParser(description="Upload video to TikTok")
    parser.add_argument("--video", required=True, help="Path to video file")
    parser.add_argument("--title", required=True, help="Video title")
    parser.add_argument("--description", default="", help="YouTube description (optional)")
    parser.add_argument("--sessionid", default=None, help="TikTok sessionid (or use TIKTOK_SESSIONID env)")

    args = parser.parse_args()

    # sessionidを取得
    sessionid = args.sessionid or os.environ.get("TIKTOK_SESSIONID")

    if not sessionid:
        print("[TikTok] Error: TIKTOK_SESSIONID is not set")
        print("[TikTok] Set it via --sessionid argument or TIKTOK_SESSIONID environment variable")
        sys.exit(1)

    # アップロード実行
    result = upload_to_tiktok(
        video_path=args.video,
        title=args.title,
        sessionid=sessionid,
        youtube_description=args.description
    )

    # Discord通知
    discord_webhook = os.environ.get("DISCORD_WEBHOOK_URL")
    if discord_webhook:
        send_discord_notification(discord_webhook, result, args.title)

    # 結果をファイルに保存（GitHub Actions用）
    result_path = "tiktok_result.json"
    with open(result_path, 'w') as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    if result["success"]:
        print("[TikTok] Done!")
        sys.exit(0)
    else:
        print(f"[TikTok] Failed: {result['error']}")
        # TikTokアップロード失敗は全体を止めない（exit 0）
        sys.exit(0)


if __name__ == "__main__":
    main()
